package com.closure;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import com.closure.common.Source;
import com.closure.utils.IO;
import com.closure.utils.Logger;
import com.closure.utils.Switches;

public class Main {
  private final static String DEPENDENCY_TEMPLATE = "goog.addDependency('%s', %s, %s);";
  
  public static void main(String[] args) {
    Switches switches = Switches.getInstance();
    String[][] required_switches = {
      {"library", "The directory to the Closure API source, 'goog'"},
      {"source", "The location where your Closure files are located."},
    };
    switches.process(args, required_switches);

    File library = new File(switches.get("library"));
    File source = new File(switches.get("source"));

    if (!library.isDirectory()) {
      Logger.info("Library path must be a directory.");
      System.exit(1);
    }

    if (!source.isDirectory()) {
      Logger.info("Source path must be a directory.");
      System.exit(1);
    }

    List<File> jsFiles = new ArrayList<File>();
    IO.getJSFiles(source, jsFiles);

    Logger.info("// This file was autogenerated by bin\\depswriter.jar");
    Logger.info("// Please do not edit.");
    
    // Process them.
    for (File target : jsFiles) {
      Source s = new Source(target);
      Logger.info(String.format(DEPENDENCY_TEMPLATE, IO.getRelativePath(target, library), s.getProvides(), s.getRequires()));
    }
  }
}
