package com.closure;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import com.closure.common.Source;
import com.closure.utils.IO;
import com.closure.utils.Logger;
import com.closure.utils.Switches;

public class Main {
  private final static String LINE_SEPARATOR = System.getProperty("line.separator");
  private final static String DEPENDENCY_TEMPLATE = "goog.addDependency('%s', %s, %s);";
  
  public static void main(String[] args) {
    Switches switches = Switches.getInstance();
    String[][] required_switches = {
      {"library", "The directory to the Closure API source, 'goog'"},
      {"source", "The location where your Closure files are located."},
      {"output", "The output location where deps file is going to be saved."},
    };
    switches.process(args, required_switches);

    File library = new File(switches.get("library"));
    File source = new File(switches.get("source"));
    File output = new File(switches.get("output"));

    if (!library.isDirectory()) {
      Logger.error("Library path must be a directory.");
      System.exit(1);
    }

    if (!source.isDirectory()) {
      Logger.error("Source path must be a directory.");
      System.exit(1);
    }
    
    if (!output.isFile()) {
      Logger.error("Output path must be a file. ex: deps.js");
      System.exit(1);
    }

    List<File> jsFiles = new ArrayList<File>();
    IO.getJSFiles(source, jsFiles);

    StringBuilder deps = new StringBuilder();
    deps.append("// This file was autogenerated by bin\\depswriter.jar" + LINE_SEPARATOR);
    deps.append("// Please do not edit." + LINE_SEPARATOR);
    
    // Process them.
    for (File target : jsFiles) {
      Source s = new Source(target);
      deps.append(String.format(DEPENDENCY_TEMPLATE + LINE_SEPARATOR, IO.getRelativePath(target, library), s.getProvides(), s.getRequires()));
    }
    
    // Write the file.
    IO.writeFile(output, deps);
    Logger.info(deps.toString());
  }
}
